posizione.o : posizione.cc posizione.h
	g++ -c posizione.cc -o posizione.o

particella.o : particella.cc particella.h
	g++ -c particella.cc -o particella.o

campovettoriale.o : campovettoriale.cc campovettoriale.h
	g++ -c campovettoriale.cc -o campovettoriale.o

puntomateriale.o : puntomateriale.cc puntomateriale.h
	g++ -c puntomateriale.cc -o puntomateriale.o